package store
import("database/sql";"fmt";"os";"path/filepath";"time";_ "modernc.org/sqlite")
type DB struct{*sql.DB}
type Trip struct{ID int64 `json:"id"`;Name string `json:"name"`;Destination string `json:"destination"`;StartDate string `json:"start_date"`;EndDate string `json:"end_date"`;Status string `json:"status"`;Notes string `json:"notes"`;TotalCostCents int64 `json:"total_cost_cents"`;CreatedAt time.Time `json:"created_at"`}
type Leg struct{ID int64 `json:"id"`;TripID int64 `json:"trip_id"`;Type string `json:"type"`;Description string `json:"description"`;Date string `json:"date"`;CostCents int64 `json:"cost_cents"`;Confirmation string `json:"confirmation"`;CreatedAt time.Time `json:"created_at"`}
func Open(d string)(*DB,error){os.MkdirAll(d,0755);dsn:=filepath.Join(d,"waystation.db")+"?_journal_mode=WAL&_busy_timeout=5000";db,err:=sql.Open("sqlite",dsn);if err!=nil{return nil,fmt.Errorf("open: %w",err)};db.SetMaxOpenConns(1);migrate(db);return &DB{db},nil}
func migrate(db *sql.DB){db.Exec(`CREATE TABLE IF NOT EXISTS trips(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,destination TEXT DEFAULT '',start_date TEXT DEFAULT '',end_date TEXT DEFAULT '',status TEXT DEFAULT 'planned',notes TEXT DEFAULT '',created_at DATETIME DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS legs(id INTEGER PRIMARY KEY AUTOINCREMENT,trip_id INTEGER NOT NULL,type TEXT DEFAULT 'flight',description TEXT NOT NULL,date TEXT DEFAULT '',cost_cents INTEGER DEFAULT 0,confirmation TEXT DEFAULT '',created_at DATETIME DEFAULT CURRENT_TIMESTAMP)`)}
func(db *DB)Create(t *Trip)error{res,err:=db.Exec(`INSERT INTO trips(name,destination,start_date,end_date,status,notes)VALUES(?,?,?,?,?,?)`,t.Name,t.Destination,t.StartDate,t.EndDate,t.Status,t.Notes);if err!=nil{return err};t.ID,_=res.LastInsertId();return nil}
func(db *DB)List()([]Trip,error){rows,_:=db.Query(`SELECT t.id,t.name,t.destination,t.start_date,t.end_date,t.status,t.notes,COALESCE(SUM(l.cost_cents),0),t.created_at FROM trips t LEFT JOIN legs l ON l.trip_id=t.id GROUP BY t.id ORDER BY t.start_date DESC`);defer rows.Close();var out[]Trip;for rows.Next(){var t Trip;rows.Scan(&t.ID,&t.Name,&t.Destination,&t.StartDate,&t.EndDate,&t.Status,&t.Notes,&t.TotalCostCents,&t.CreatedAt);out=append(out,t)};return out,nil}
func(db *DB)AddLeg(l *Leg)error{res,err:=db.Exec(`INSERT INTO legs(trip_id,type,description,date,cost_cents,confirmation)VALUES(?,?,?,?,?,?)`,l.TripID,l.Type,l.Description,l.Date,l.CostCents,l.Confirmation);if err!=nil{return err};l.ID,_=res.LastInsertId();return nil}
func(db *DB)ListLegs(tripID int64)([]Leg,error){rows,_:=db.Query(`SELECT id,trip_id,type,description,date,cost_cents,confirmation,created_at FROM legs WHERE trip_id=? ORDER BY date,created_at`,tripID);defer rows.Close();var out[]Leg;for rows.Next(){var l Leg;rows.Scan(&l.ID,&l.TripID,&l.Type,&l.Description,&l.Date,&l.CostCents,&l.Confirmation,&l.CreatedAt);out=append(out,l)};return out,nil}
func(db *DB)Delete(id int64){db.Exec(`DELETE FROM legs WHERE trip_id=?`,id);db.Exec(`DELETE FROM trips WHERE id=?`,id)}
func(db *DB)Stats()(map[string]interface{},error){var trips int;var cost int64;db.QueryRow(`SELECT COUNT(*) FROM trips`).Scan(&trips);db.QueryRow(`SELECT COALESCE(SUM(cost_cents),0) FROM legs`).Scan(&cost);return map[string]interface{}{"trips":trips,"total_cost_cents":cost},nil}
